apiVersion: apps/v1
kind: Deployment
metadata:
  name: e-commerce-app-deployment
  namespace: e-commerce-app
  labels:
    app: e-commerce-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: e-commerce-app
  template:
    metadata:
      labels:
        app: e-commerce-app
    spec:
      containers:
        - name: e-commerce-app
          image: zeeshankanuga/e-commerce-app:1
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: e-commerce-app-config
            - secretRef:
                name: e-commerce-app-secret

          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
      
          startupProbe:
                httpGet:
                path: /
                port: 3000
                failureThreshold: 30
                periodSeconds: 10
          readinessProbe:
                httpGet:
                path: /
                port: 3000
                initialDelaySeconds: 20
                periodSeconds: 10
          livenessProbe:
                httpGet:
                path: /
                port: 3000
                initialDelaySeconds: 30
                periodSeconds: 10

