apiVersion: v1
kind: service
metadata:
  name: mongo-service
  namespace: e-commerce-app
  labels:
    app: mongo
spec:
  selector:
    app: mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017