apiVersion: v1
kind: job
metadata:
  name: db-migration-job
  namespace: e-commerce-app
spec:
  template:
    spec:
      containers:
        - name: db-migration
          image: zeeshankanuga/db-migration:1
          imagePullPolicy: Always
          env:
            - name: MONGO_URI
              value: "mongodb://mongo-service:27017/ecommerce"
      restartPolicy: OnFailure